export const productos = [ 
    {
        id: 11,
        nombre: 'guante',
        img: '91hrxclt9YL.__AC_SX300_SY300_QL70_FMwebp_.webp',
        descripcion: ' Guante de béisbol y sóftbol',
        precio:20000,
        categoria: 'baseball',
    },
    {
        id: 12,
        nombre: 'bate',
        img: '617TJdtb-4L._AC_SX569_.jpg',
        descripcion: 'Bate de Béisbol para niños y jóvenes - Aluminio - aprobados para béisbol en EE. UU.',  
        precio:20000,
        categoria: 'baseball', 
    },
    {
        id: 13,
        nombre: 'pelotas',
        img: '81KbuSuq+uL._AC_SX569_.jpg',
        descripcion: ' Pelotas de béisbol de práctica de uso recreativo de la liga oficial',  
        precio:20000,
        categoria: 'baseball',
    },
    {
        id: 14,
        nombre: 'morral',
        img: '612aC+btTPL._AC_SY300_SX300_.jpg',
        descripcion: ' Morral para bate y equipo de sóftbol y béisbol, 2 bolsillos para bate ', 
        precio:20000,
        categoria: 'baseball', 
    },
    {
        id: 15,
        nombre: 'cinta',
        img: '61dufxEkDEL.__AC_SX300_SY300_QL70_FMwebp_.webp',
        descripcion: 'Agarre de murciélago de 0.043 in, cinta de béisbol y sóftbol de última generación',  
        precio:20000,
        categoria: 'baseball',
   },
   {
        id: 16,
        nombre: 'combo',
        img: '81RPNnEUwYL._AC_SX569_.jpg',
        descripcion: 'Combo de guante y pelota ',  
        precio:20000,
        categoria: 'baseball',
   },
   {
        id: 17,
        nombre: 'pelota oficial',
        img: '81ixmVcyc9L._AC_SX569_.jpg',
        descripcion: 'pelota oficial de la liga mayor de béisbol',  
        precio:20000,
        categoria: 'baseball',
   },
   {
        id: 18,
        nombre: 'kit',
        img: '81ixmVcyc9L._AC_SX569_.jpg',
        descripcion: 'Kit de entrenamiento de lanzamiento de baseball',  
        precio:20000,
        categoria: 'baseball',
   },
   {
        id: 19,
        nombre: 'resina',
        img: '61GEq3tKu2L._AC_SX569_.jpg',
        descripcion: 'Resina de pino para bate de béisbol',  
        precio:20000,
        categoria: 'baseball',
    },
    {
        id: 10,
        nombre: 'envoltura',
        img: '61YFD3diuQL._AC_SX569_.jpg',
        descripcion: 'Envoltura para guantes ',  
        precio:20000,
        categoria: 'baseball',
    },
    {
        id: 21,
        nombre: 'balon wilson',
        img: '81pkjvvZcjL._AC_SX569_.jpg',
        descripcion: 'Wilson, NBA DRV Series Baloncesto al aire libre',
        precio:20000,
        categoria: 'basketball',
    },
    {
        id: 22,
        nombre: 'balon spalding',
        img: '81eNOCqjp+L._AC_SX425_.jpg',
        descripcion: 'Spalding Street Phantom Outdoor Basketball ',   
        precio:20000,
        categoria: 'basketball',
    },
    {
        id: 23,
        nombre: 'balon AND1',
        img: '91MNBT7r3JL._AC_SX425_.jpg',
        descripcion: 'AND1 Street Grip - Balón de baloncesto de cuero compuesto y kit de inflado',  
        precio:20000,
        categoria: 'basketball',
    },
    {
        id: 24,
        nombre: 'combo canasta',
        img: '51vJe512YKL._AC_SX425_.jpg',
        descripcion: ' Canasta de baloncesto mas balon',  
        precio:20000,
        categoria: 'basketball',
    },
    {
        id: 25,
        nombre: 'mini aro',
        img: '81m7xAlpPUL._AC_SX569_.jpg',
        descripcion: 'Mini aro de baloncesto para interiores y 4 bolas para puerta',  
        precio:20000,
        categoria: 'basketball',
    },
    {
        id: 26,
        nombre: 'balones multicolores',
        img: '71IS8u53OWS._AC_SX679_.jpg',
        descripcion: 'MacGregor Balones de baloncesto multicolor',  
        precio:20000,
        categoria: 'basketball',
    },
    {
        id: 27,
        nombre: 'aros led',
        img: '71g88y8H3WS._AC_SX425_.jpg',
        descripcion: 'aros de luz led',  
        precio:20000,
        categoria: 'basketball',
    },
    {
        id: 28,
        nombre: 'estante',
        img: '811LCtNnHfL._AC_SX569_.jpg',
        descripcion: 'Estante de baloncesto',  
        precio:20000,
        categoria: 'basketball',
    },
    {
        id: 29,
        nombre: 'marcador',
        img: '71l3rzhFL-L._AC_SX569_.jpg',
        descripcion: 'marcador de puntuación para deportes de interior y exterior',  
        precio:20000,
        categoria: 'basketball',
    },
    {
        id: 20,
        nombre: 'Coderas',
        img: '816ITSX86OL._SX466_.jpg',
        descripcion: 'Coderas para hombres y mujeres baloncesto', 
        precio:20000,
        categoria: 'basketball',
    },
    { 
        id: 31,
        nombre: 'balon de futbol',
        img: '61jU4o9laBL._AC_SX569_.jpg',
        descripcion: 'WILSON Balón de fútbol tradicional',
        precio:20000,
        categoria: 'futbol',
    },
    {
        id: 32,
        nombre: 'balon mundial qatar',
        img: '81ZxOXUwFsL._AC_SX569_.jpg',
        descripcion: 'Balón de fútbol de Al Rihla Club',   
        precio:20000,
        categoria: 'futbol',
    },
    {
        id: 33,
        nombre: 'Botines de fútbol',
        img: '610COJlTH4L._AC_UY500_.jpg',
        descripcion: 'Botines de fútbol para hombre',  
        precio:20000,
        categoria: 'futbol',
    },
    {
        id: 34,
        nombre: 'Tacos de fútbol',
        img: '51itaYeX7qL._AC_UY625_.jpg',
        descripcion: 'Tacos de fútbol ligeros y firmes para hombre', 
        precio:20000,
        categoria: 'futbol', 
    },
    {
        id: 35,
        nombre: 'Zapatos de fútbol',
        img: '71D-Sx6lmvL._AC_UY625_.jpg',
        descripcion: 'Zapatos de fútbol para hombre',  
        precio:20000,
        categoria: 'futbol',
    },
    {
        id: 36,
        nombre: 'red para porteria',
        img: '81AEUyAa00L.__AC_SY300_SX300_QL70_FMwebp_.webp',
        descripcion: ' Red de nailon de repuesto para portería',  
        precio:20000,
        categoria: 'futbol',
    },
    {
        id: 37,
        nombre: 'Portería de fútbol',
        img: '81afswy9TOL._AC_SX569_.jpg',
        descripcion: 'Portería de fútbol portátil para niños ',  
        precio:20000,
        categoria: 'futbol',
    },
    {
        id: 38,
        nombre: 'porteria para adultos',
        img: '91TygTEEwtL._AC_SX569_.jpg',
        descripcion: 'Portería de fútbol para adultos',  
        precio:20000,
        categoria: 'futbol',
    },
    {
        id: 39,
        nombre: 'conos',
        img: '51NeKULUxAL.__AC_SX300_SY300_QL70_FMwebp_.webp',
        descripcion: 'Conos de entrenamiento de fútbol ',  
        precio:20000,
        categoria: 'futbol',
    },
    {
        id: 30,
        nombre: 'kit de futbol',
        img: '71ePQvmIdxS._AC_SX569_.jpg',
        descripcion: 'kit de entrenamiento de futbol', 
        precio:20000,
        categoria: 'futbol',
    },
    { 
        id: 41,
        nombre: 'raqueta wilson',
        img: '71d-NCUzaLL._AC_SX569_.jpg',
        descripcion: 'Raqueta de tenis recreativa para adultos',
        precio:20000,
        categoria: 'tennis',
    },
    {
        id: 42,
        nombre: 'raqueta teloon',
        img: '81fkUrupmeL._AC_SX569_.jpg',
        descripcion: 'Teloon Raquetas de tenis para adultos',   
        precio:20000,
        categoria: 'tennis',
    },
    {
        id: 43,
        nombre: 'pelotas wilson',
        img: '71iG-PCBEKS._AC_SX425_.jpg',
        descripcion: 'WILSON Pelotas de tenis de campeonato',  
        precio:20000,
        categoria: 'tennis',
    },
    {
        id: 44,
        nombre: 'pelotas penn',
        img: '71iJpHMLKBL._AC_SX425_.jpg',
        descripcion: 'Penn Championship - Pelotas de tenis ',  
        precio:20000,
        categoria: 'tennis',
    },
    {
        id: 45,
        nombre: 'Cinta de agarre ',
        img: '81dbxptHMHL._AC_SX569_.jpg',
        descripcion: 'Cinta de agarre para raqueta de tenis ',  
        precio:20000,
        categoria: 'tennis',
    },
    {
        id: 46,
        nombre: 'postal',
        img: '51zlrhFjuML._SY445_.jpg',
        descripcion: 'postal Open Mens Tennis Final - Nadal vs Djokovic',  
        precio:20000,
        categoria: 'tennis',
    },
    {
        id: 47,
        nombre: 'Bolsa de tenis',
        img: '81HAKbnn19L._AC_SX569_.jpg',
        descripcion: 'Bolsa de tenis para hombres y mujeres para sostener 2 raquetas',  
        precio:20000,
        categoria: 'tennis',
    },
    {
        id: 48,
        nombre: 'vestido',
        img: '61pa2QEm8wL._AC_UY741_.jpg',
        descripcion: 'Vestido de tenis para mujer',  
        precio:20000,
        categoria: 'tennis',
    },
    {
        id: 49,
        nombre: 'bolso 3 raquetas',
        img: '71MUEF8J61L._AC_SX425_.jpg',
        descripcion: 'Bolsa de tenis de 3 raquetas',  
        precio:20000,
        categoria: 'tennis',
    },
    {
        id: 40,
        nombre: 'Muñequeras',
        img: '61pjRlD0kJL._AC_UX679_.jpg',
        descripcion: 'Muñequeras de 3 pulgadas para hombre', 
        precio:20000,
        categoria: 'tennis',
    },
    {
        id: 51,
        nombre: 'lentes',
        img: '41beY0tC10L._AC_UY625_.jpg',
        descripcion: 'Lentes de sol con protección de béisbol',
        precio:20000,
        categoria: 'otros',
    },
    {
        id: 52,
        nombre: 'bandas',
        img: '71XSLy1U8SL._AC_SX569_.jpg',
        descripcion: 'Bandas para el sudor para hombre',   
        precio:20000,
        categoria: 'otros',
    },
    {
        id: 53,
        nombre: 'botella',
        img: '71ipBpmK-qL._AC_SY606_.jpg',
        descripcion: 'Botella de agua motivacional de 32 onzas', 
        precio:20000,
        categoria: 'otros', 
    },
    {
        id: 54,
        nombre: 'guantes',
        img: '71ciydddyyL._AC_SX569_.jpg',
        descripcion: 'guantes para ejercicios de gym',  
        precio:20000,
        categoria: 'otros',
    },
    {
        id: 55,
        nombre: 'camara',
        img: '71WcMm-3rsL._AC_SX425_.jpg',
        descripcion: ' cámara deportiva Full HD',  
        precio:20000,
        categoria: 'otros',
    
    },
]